#!/usr/bin/env bash

CAPABILITY_SUBMENU="submenu"
CAPABILITY_ITEM_REMOVAL="remove"
CAPABILITY_BATCH="batch"
CAPABILITY_REQUIRE_INIT="init"
CAPABILITY_SELECT_LAST_ITEM="lastitem"

export CAPABILITY_SUBMENU
export CAPABILITY_ITEM_REMOVAL
export CAPABILITY_BATCH
export CAPABILITY_REQUIRE_INIT
export CAPABILITY_SELECT_LAST_ITEM
